### PR TITLE
fix(Table): fix flattenData function

### PR DESCRIPTION
**Pull request by Edymov**
Fixed flattenData inner function loop. Previous function implementation was often caused an error **Cannot add property Symbol(parent), object is not extensible**
Fixed ts types

### CODE REVIEW

**Comment by simonguo** [comment]
Hi @Edymov

You can install the current PR-fixed version through the following installation path to check whether the existing problems are fixed.

```
npm i https://pkg.csb.dev/rsuite/rsuite-table/commit/e91c7306/rsuite-table
```

Also I hope you can add a test for `flattenData`. 

Thanks

**Comment by Edymov** [comment]
I installed new version and test it just few minutes ago. It works. I can add some tests. What kind of tests it should be?

**Comment by Edymov** [comment]
Can you merge PR now?

**Comment by simonguo** [comment]
Hi @Edymov  this PR will be Reverted as it leads to a new bug.  https://github.com/rsuite/rsuite-table/issues/416

**Pull request merged**
