### PR TITLE
feat(Table): support renderRow on <Table>

### PR DESCRIPTION
**Pull request by simonguo**
close https://github.com/rsuite/rsuite/issues/2238

## Usage

```jsx
<Table
  renderRow={(children, rowData) =>
    rowData && rowData.id === 1 ? <div className="custom-row">{children}</div> : children
  }
>
...
</Table>
```

----

Use `renderRow` to achieve row drag sorting.

https://user-images.githubusercontent.com/1203827/146856338-7d6e3829-78c6-4b9f-9914-62420092b811.mp4

### CODE REVIEW

**Comment by raibikys** [comment]
Nice!

**Comment by raibikys** [comment]
Is there any info when should this feature be released? @simonguo

**Comment by raibikys** [comment]
@simonguo  could you provide please an example how did you achieved such drag&drop with adaptive borders when dragging over another row?

**Comment by simonguo** [comment]
Released in [rsuite@5.4.3](https://github.com/rsuite/rsuite/releases/tag/v5.4.3)

**Pull request merged**
